name: Gilded Netherite Build Script

on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [ 8, 11, 16]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache

      - name: Build Gilded Netherite
        run: |
          ./gradlew clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gilded-netherite-artifact
          path: '**/build/libs/*.jar'